default_platform(:ios)

platform :ios do
  desc "Build and upload to App Store Connect"
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
    )

    sync_code_signing(
      type: "appstore",
      api_key: api_key,
      readonly: is_ci,
    )

    build_ios_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      output_directory: "build/ios/ipa",
      output_name: "pixela_buttons",
      xcargs: "CODE_SIGN_STYLE=Manual",
    )

    upload_to_app_store(
      api_key: api_key,
      ipa: "build/ios/ipa/pixela_buttons.ipa",
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,
    )
  end
end
