default_platform(:ios)

platform :ios do
  desc "Build and upload to App Store Connect"
  lane :deploy do
    setup_ci if is_ci

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
    )

    sync_code_signing(
      type: "appstore",
      api_key: api_key,
      readonly: is_ci,
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/Runner.xcodeproj",
      code_sign_identity: "iPhone Distribution",
      profile_name: "match AppStore com.a-know.pixelaButtons",
    )

    build_ios_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      output_directory: "build/ios/ipa",
      output_name: "pixela_buttons",
      xcargs: "ENABLE_USER_SCRIPT_SANDBOXING=NO",
      clean: true,
    )

    upload_to_app_store(
      api_key: api_key,
      ipa: "build/ios/ipa/pixela_buttons.ipa",
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,
    )
  end
end
